"""Initial schema (docs/03-data-model.md).

Day-0 pattern: this first migration creates the required Postgres extensions and
then materializes the ORM metadata directly, so migration #1 is in sync with the
models by construction. Every subsequent schema change must be a real
autogenerated/hand-written Alembic diff.
"""

from alembic import op

from senthire.db import models  # noqa: F401  — populate metadata
from senthire.db.base import Base

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)
    # HNSW index for cosine similarity (docs/03 §2)
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_embeddings_vector_hnsw "
        "ON embeddings USING hnsw (vector vector_cosine_ops)"
    )


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
